[
tool.poetry
]
name = "whalers5"
version = "0.1.0"
description = ""
authors = ["whalers5 <whalers5@163.com>"]

[
tool.poetry.dependencies
]
python = "^3.11"
aiohappyeyeballs = "2.4.4"
aiohttp = "3.11.10"
aiosignal = "1.3.2"
attrs = "24.3.0"
click = "8.1.8"
colorama = "0.4.6"
frozenlist = "1.5.0"
h11 = "0.14.0"
idna = "3.10"
multidict = "6.1.0"
numpy = "2.1.3"
propcache = "0.2.1"
uvicorn = "0.34.0"
yarl = "1.18.3"

[
build-system
]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"